version: 0.0
os: linux
Resources:
  - TargetService:
      Type: AWS::EC2::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "sample-website"
          ContainerPort: 80
